function [fitresult, gof] = createFits(xxrad, med)
%CREATEFITS(XXRAD,MED)
%  Create fits.
%
%  Data for 'sinpp' fit:
%      X Input : xxrad
%      Y Output: med
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Mar-2018 17:31:30

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'sinpp'.
[xData, yData] = prepareCurveData( xxrad, med );

% Set up fittype and options.
ft = fittype( 'sin5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [29.0670338658103 1.01694915254237 -0.0390604214171713 12.7945147761673 2.03389830508475 1.49138427380757 4.18845451455966 4.06779661016949 1.44619317660248 0.864709859348959 8.13559322033898 1.30973328533568 0.75298625111291 6.10169491525424 1.32101110666719];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'sinpp' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'med vs. xxrad', 'sinpp', 'Location', 'NorthEast' );
% Label axes
xlabel xxrad
ylabel med
grid on

%% Fit: 'untitled fit 2'.
% Cannot generate code for fit 'untitled fit 2' because the data selection is incomplete.


